---

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates single EC2 instance in public subnet in VPC network to
  work on simple tasks. VPC stack has to exist before creation.
Metadata: {}
Parameters:
  VPCStackName:
    Description: VPC network stack name. It must export "VPCID" and subnet ID specified by VPCSubnetID parameter.
    Type: String
  VPCSubnetID:
    Description: Exported variable name of Subnet ID in VPC stack.
    Default: PublicSubnet1ID
    Type: String
  WorkerAMIOS:
    AllowedValues:
      - Amazon-Linux-HVM
    Default: Amazon-Linux-HVM
    Description: The Linux distribution for the AMI to be used for the worker instances
    Type: String
  WorkerInstanceType:
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
    Default: t2.micro
    Description: Amazon EC2 instance type for the worker instances
    Type: String
  WorkerDiskSize:
    Default: 8
    Description: Disk size by GB
    Type: Number
    MinValue: 8
    MaxValue: 100
  WorkerProfile:
    Default: ""
    Description: Instance profile to attach the worker instances. Its role have to be allowed to put CloudWatch Logs.
    Type: String
  KeyPairName:
    Description: >-
      Enter a Public/private key pair. If you do not have one in this region,
      please create it before continuing
    Type: 'AWS::EC2::KeyPair::KeyName'
  CloudWatchLogsGroup:
    Default: "/var/log/jupyterlab.log"
    Description: Group name of CloudWatch Logs to deliver Jupyter Lab server log.
    Type: String
  RemoteAccessCIDR1:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the worker
    Type: String
  RemoteAccessCIDR2:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the worker
    Default: 0.0.0.0/0
    Type: String
  RemoteAccessCIDR3:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the worker
    Default: 0.0.0.0/0
    Type: String
  RemoteAccessCIDR4:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the worker
    Default: 0.0.0.0/0
    Type: String
  WebAccessCIDR1:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for web access
    Type: String
  WebAccessCIDR2:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for web access
    Default: 0.0.0.0/0
    Type: String
  WebAccessCIDR3:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for web access
    Default: 0.0.0.0/0
    Type: String
  WebAccessCIDR4:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for web access
    Default: 0.0.0.0/0
    Type: String
Conditions:
  UseInstanceProfile:
    !Not [!Equals [!Ref WorkerProfile, ""]]
  UseRemoteAccessCIDR2:
    !Not [!Equals [!Ref RemoteAccessCIDR2, "0.0.0.0/0"]]
  UseRemoteAccessCIDR3:
    !Not [!Equals [!Ref RemoteAccessCIDR3, "0.0.0.0/0"]]
  UseRemoteAccessCIDR4:
    !Not [!Equals [!Ref RemoteAccessCIDR4, "0.0.0.0/0"]]
  UseWebAccessCIDR2:
    !Not [!Equals [!Ref WebAccessCIDR2, "0.0.0.0/0"]]
  UseWebAccessCIDR3:
    !Not [!Equals [!Ref WebAccessCIDR3, "0.0.0.0/0"]]
  UseWebAccessCIDR4:
    !Not [!Equals [!Ref WebAccessCIDR4, "0.0.0.0/0"]]
Resources:
  WaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
  WaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: Worker
    Properties:
      Handle: !Ref WaitHandle
      Timeout: '1200'
  RemoteAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH Access to Worker Hosts
      VpcId:
        Fn::ImportValue:
          !Sub "${VPCStackName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref RemoteAccessCIDR1
        - IpProtocol: icmp
          FromPort: "-1"
          ToPort: "-1"
          CidrIp: !Ref RemoteAccessCIDR1
        - !If
            - UseRemoteAccessCIDR2
            - IpProtocol: tcp
              FromPort: "22"
              ToPort: "22"
              CidrIp: !Ref RemoteAccessCIDR2
            - !Ref "AWS::NoValue"
        - !If
            - UseRemoteAccessCIDR3
            - IpProtocol: tcp
              FromPort: "22"
              ToPort: "22"
              CidrIp: !Ref RemoteAccessCIDR3
            - !Ref "AWS::NoValue"
        - !If
            - UseRemoteAccessCIDR4
            - IpProtocol: tcp
              FromPort: "22"
              ToPort: "22"
              CidrIp: !Ref RemoteAccessCIDR4
            - !Ref "AWS::NoValue"
      Tags:
        - Key: Name
          Value: SSHAccessToJupyterLab
        - Key: Network
          Value: Public
  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables Web Access to Hosts
      VpcId:
        Fn::ImportValue:
          !Sub "${VPCStackName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "8888"
          ToPort: "8888"
          CidrIp: !Ref WebAccessCIDR1
        - !If
            - UseWebAccessCIDR2
            - IpProtocol: tcp
              FromPort: "8888"
              ToPort: "8888"
              CidrIp: !Ref WebAccessCIDR2
            - !Ref "AWS::NoValue"
        - !If
            - UseWebAccessCIDR3
            - IpProtocol: tcp
              FromPort: "8888"
              ToPort: "8888"
              CidrIp: !Ref WebAccessCIDR3
            - !Ref "AWS::NoValue"
        - !If
            - UseWebAccessCIDR4
            - IpProtocol: tcp
              FromPort: "8888"
              ToPort: "8888"
              CidrIp: !Ref WebAccessCIDR4
            - !Ref "AWS::NoValue"
      Tags:
        - Key: Name
          Value: WebAccessToJupyterLab
        - Key: Network
          Value: Public
  Worker:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          OnCreate: [account, setup, pkg_amazonlinux, cfg, cfg_amazonlinux, svc_amazonlinux, svc]
        account:
          users:
            jupyter:
              homeDir: /opt/jupyter
        setup:
          files:
            /opt/local/bin/default-awsconfig.sh:
              content: |
                #!/bin/sh -v
                [ -d ~/.aws ] || mkdir ~/.aws
                chmod 700 ~/.aws
                cp /opt/local/etc/default-awsconfig ~/.aws/config
                chmod 600 ~/.aws/config
              mode: "000755"
              owner: "root"
              group: "root"
            /opt/local/etc/default-awsconfig:
              content: !Sub |
                [default]
                region = ${AWS::Region}
              mode: "000644"
              owner: "root"
              group: "root"
            /opt/jupyter/server/Pipfile:
              content: |
                [[source]]
                url = "https://pypi.python.org/simple"
                verify_ssl = true
                name = "pypi"
                [packages]
                jupyterlab = "*"
                numpy = "*"
                scipy = "*"
                matplotlib = "*"
                pandas = "*"
                statsmodels = "*"
                seaborn = "*"
                bokeh = "*"
                tensorflow = "*"
                pyyaml = "*"
                boto3 = "*"
              mode: "000644"
              owner: "jupyter"
              group: "jupyter"
            /opt/jupyter/notebook/README.md:
              content: |
                # Jupyter Lab

                Files in this folder will not be saved permanently.
                Please backup notebooks and data files on S3 bucket.
              mode: "000644"
              owner: "jupyter"
              group: "jupyter"
            /opt/jupyter/bin/jupyterlab.sh:
              content: |
                #!/bin/sh -v
                export PATH=$PATH:/usr/local/bin
                jupyter_dir=/opt/jupyter/server
                notebook_dir=/opt/jupyter/notebook
                logfile=$1
                cd $jupyter_dir
                pipenv install
                echo "To generate password: pipenv run jupyter notebook password"
                nohup pipenv run jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=$notebook_dir > $logfile 2>&1 &
              mode: "000755"
              owner: "jupyter"
              group: "jupyter"
        pkg_amazonlinux:
          packages:
            yum:
              git: []
              python36-pip: []
              awslogs: []
        cfg:
          files:
            /var/log/jupyterlab.log:
              content: |
                Generated by AWS::CloudFormation::Init
              mode: "000644"
              owner: "jupyter"
              group: "jupyter"
        cfg_amazonlinux:
          files:
            /etc/awslogs/awscli.conf:
              content: !Sub |
                [plugins]
                cwlogs = cwlogs
                [default]
                region = ${AWS::Region}
            /etc/awslogs/awslogs.conf:
              content: !Sub |
                [general]
                state_file = /var/lib/awslogs/agent-state

                [/var/log/jupyterlab.log]
                datetime_format = %b %d %H:%M:%S
                file = /var/log/jupyterlab.log
                buffer_duration = 5000
                log_stream_name = {instance_id}
                initial_position = start_of_file
                log_group_name = ${CloudWatchLogsGroup}
              mode: "000644"
              owner: "root"
              group: "root"
          commands:
            pip:
              command: |
                # pip-3.6 install -U pip
                pip-3.6 install pipenv
        svc:
          commands:
            jupyterlab:
              command: |
                chown -R jupyter:jupyter /opt/jupyter
                sudo -u jupyter /opt/jupyter/bin/jupyterlab.sh /var/log/jupyterlab.log
        svc_amazonlinux:
          services:
            sysvinit:
              awslogs:
                enabled: "true"
                ensureRunning: "true"
    Properties:
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !If [UseInstanceProfile, !Ref WorkerProfile, !Ref "AWS::NoValue"]
      ImageId: !FindInMap [AWSAMIRegionMap, !Ref "AWS::Region", !FindInMap [LinuxAMINameMap, !Ref WorkerAMIOS, Code]]
      SecurityGroupIds:
        - !Ref RemoteAccessSecurityGroup
        - !Ref WebAccessSecurityGroup
      SubnetId:
        Fn::ImportValue:
          !Sub "${VPCStackName}-${VPCSubnetID}"
      InstanceType: !Ref WorkerInstanceType
      BlockDeviceMappings:
        - DeviceName: !FindInMap [LinuxAMINameMap, !Ref WorkerAMIOS, RootDevice]
          Ebs:
            VolumeSize: !Ref WorkerDiskSize
            VolumeType: gp2
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash -v
            # Extend PATH variable for `cfn-init` and `cfn-signal`
            if [ "${WorkerAMIOS}" == "Amazon-Linux-HVM" ]; then
              export PATH=$PATH:/opt/aws/bin
            else
              export PATH=$PATH:/usr/local/bin
            fi
            # Helper function
            function error_exit {
              cfn-signal -e 1 -r "$1" "${WaitHandle}"
              exit 1
            }
            ${Packager} update -y
            if [ "${WorkerAMIOS}" == "Amazon-Linux-HVM" ]; then
              ${Packager} install -y aws-cfn-bootstrap
              configsets=OnCreate
            elif [ "${WorkerAMIOS}" == "Ubuntu-Server-16.04-LTS-HVM" ]; then
              ${Packager} install -y python-pip
              # Use Python 2.x for aws-cfn-bootstrap
              pip install -U pip
              pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
              configsets=OnCreateUbuntu
            else
              error_exit 'unhandled OS type ${WorkerAMIOS}'
            fi
            cfn-init --stack ${AWS::StackId} --resource Worker --configsets $configsets --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
            cfn-signal -e 0 -r "Worker setup complete" "${WaitHandle}"
          - Packager: !FindInMap [LinuxAMINameMap, !Ref WorkerAMIOS, Packager]
      Tags:
        - Key: Name
          Value: JupyterLab
  WorkerEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref Worker
Outputs:
  WorkerEIP:
    Description: Public IP address of worker
    Value: !Ref WorkerEIP
  SSHAccess:
    Description: SSH access target
    Value: !Join ["@", [!FindInMap [LinuxAMINameMap, !Ref WorkerAMIOS, User], !Ref WorkerEIP]]
  WebAccess:
    Description: Web access URL
    Value: !Sub 'http://${WorkerEIP}:8888/'
Mappings:
  # Derived from "quickstart-linux-bastion"
  AWSAMIRegionMap:
    AMI:
      AMZNLINUXHVM: amzn-ami-hvm-2017.09.1.20180108-x86_64-gp2
    ap-northeast-1:
      AMZNLINUXHVM: ami-33c25b55
    ap-northeast-2:
      AMZNLINUXHVM: ami-d9b616b7
    ap-south-1:
      AMZNLINUXHVM: ami-fedb8f91
    ap-southeast-1:
      AMZNLINUXHVM: ami-889cecf4
    ap-southeast-2:
      AMZNLINUXHVM: ami-ccab56ae
    ca-central-1:
      AMZNLINUXHVM: ami-61f97c05
    eu-central-1:
      AMZNLINUXHVM: ami-0fc85a60
    eu-west-1:
      AMZNLINUXHVM: ami-e487179d
    eu-west-2:
      AMZNLINUXHVM: ami-51809835
    eu-west-3:
      AMZNLINUXHVM: ami-fe03b483
    sa-east-1:
      AMZNLINUXHVM: ami-1226647e
    us-east-1:
      AMZNLINUXHVM: ami-cb9ec1b1
    us-east-2:
      AMZNLINUXHVM: ami-caaf84af
    us-west-1:
      AMZNLINUXHVM: ami-95eeeef5
    us-west-2:
      AMZNLINUXHVM: ami-32cf7b4a
  LinuxAMINameMap:
    Amazon-Linux-HVM:
      Code: AMZNLINUXHVM
      RootDevice: /dev/xvda
      User: ec2-user
      Packager: yum
